pipelines:
  default:
    - step:
        name: Build and Push Docker
        image: atlassian/default-image:4
        size: 4x  # 16 GB RAM, 8 CPU (dedicated)
        services:
          - docker

        script:
          - |
            time_cmd() {
              start=$(date +%s)
              "$@"
              end=$(date +%s)
              echo "$* took $((end-start)) seconds"
            }
          - time_cmd git clone https://github.com/immich-app/immich.git
          - cd immich

          # Build Docker image
          - time_cmd docker build -t $DOCKER_REGISTRY/immich-server-bitbucket:$BITBUCKET_COMMIT -f server/Dockerfile .
          - time_cmd docker tag $DOCKER_REGISTRY/immich-server-bitbucket:$BITBUCKET_COMMIT $DOCKER_REGISTRY/immich-server-bitbucket:latest
          
          # Login to Docker registry
          - time_cmd sh -c 'echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin'

          # Push Docker images
          - time_cmd sh -c 'docker push $DOCKER_REGISTRY/immich-server-bitbucket:$BITBUCKET_COMMIT && docker push $DOCKER_REGISTRY/immich-server-bitbucket:latest'

# Set memory limit for DiD to prevent issues OOM during build
definitions:
  services:
    docker:
      memory: 4096 