name: Build and push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # run at 04:50, 04:55 (UTC) every day
      - cron: '50 3 * * *'
      - cron: '55 3 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest # 4 vCPU, 16 GB RAM (for public-repo)
    permissions:
      contents: read
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: immich-app/immich

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: server/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/immich-server-github:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/immich-server-github:${{ github.sha }}