name: Build and push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # he schedule runs every 30 minutes
    # from 17:30 on February 16 to 03:00 on February 17 in Berlin time
      - cron: '30/30 16-23 16 2 *'
      - cron: '0/30 0-2 17 2 *'

jobs:
  build-and-push:
    runs-on: ubuntu-22.04 # 4 vCPU, 16 GB RAM (for public-repo)
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: immich-app/immich

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: server/Dockerfile
          push: false  # ! Only build without push!
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/immich-server-github:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/immich-server-github:${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/immich-server-github:latest
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/immich-server-github:${{ github.sha }}